### ISSUE TITLE
Error 500 by accessing "My Account"

### ISSUE THREAD

**Issue by CSCSxx** [dhanasingh/redmine_wktime#235]
After upgrading ERPMine to 4.1.2 i got following error when i try to access to my Account:

Started GET "/my/account" for 127.0.0.1 at 2021-03-25 11:28:13 +0000
Processing by MyController#account as HTML
  Current user: technik (id=5)
  Rendering my/account.html.erb within layouts/base
  Rendered plugins/redmine_wktime/app/views/wkuser/_wk_user.html.erb (306.5ms)
  Rendered users/_mail_notifications.html.erb (42.7ms)
  Rendered users/_preferences.html.erb (70.4ms)
  Rendered plugins/redmine_wktime/app/views/wklead/_contact_info.html.erb (6.3ms)
  Rendered plugins/redmine_wktime/app/views/wkuser/_wk_user_address.html.erb (14.7ms)
  Rendered my/account.html.erb within layouts/base (464.5ms)
Completed 500 Internal Server Error in 594ms (ActiveRecord: 319.9ms)
  
ActionView::Template::Error (undefined method `source_type' for #<WkUser:0x000000000674bf48>):
     8: 	<div>
     9: 		<%= hidden_field_tag "attachment_ids", "" %>
    10: 		<%= labelled_fields_for :erpmineuser, @user&.erpmineuser do |f| %>
    11: 			<%= f.hidden_field "source_type" %>
    12: 			<%= f.hidden_field "source_id" %>
    13: 		<% end %>
    14: 		<%= render partial: "wkdocument/attachment_form", locals: { container: @user, container_type: "Principal" } %>
  
plugins/redmine_wktime/app/views/wkuser/_wk_user_address.html.erb:11:in `block in _d8ea15cac5a60ea4a6fb4fecb234144e'
app/helpers/application_helper.rb:1365:in `labelled_fields_for'
plugins/redmine_wktime/app/views/wkuser/_wk_user_address.html.erb:10:in `_d8ea15cac5a60ea4a6fb4fecb234144e'
lib/redmine/hook/view_listener.rb:61:in `block (2 levels) in render_on'
lib/redmine/hook/view_listener.rb:59:in `map'
lib/redmine/hook/view_listener.rb:59:in `block in render_on'
lib/redmine/hook.rb:63:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `block in call_hook'
lib/redmine/hook.rb:60:in `tap'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:98:in `call_hook'
app/views/my/account.html.erb:50:in `block in _55c59bc7581967e4dc52c937e0d1f790'
app/helpers/application_helper.rb:1358:in `labelled_form_for'
app/views/my/account.html.erb:14:in `_55c59bc7581967e4dc52c937e0d1f790'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:60:in `call'

Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.4.10-p364 (2020-03-31) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.3
  Mercurial                      3.7.3
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.28.0
  Filesystem                     
Redmine plugins:
  additionals                    3.0.2-master
  mobile_issue_table             0.0.1
  redmine_checklists             3.1.18
  redmine_ckeditor               1.2.3
  redmine_contacts               4.3.2
  redmine_dmsf                   2.4.5
  redmine_issue_dynamic_edit     0.7.2
  redmine_issue_todo_lists       1.3
  redmine_issue_view_columns     1.0.1
  redmine_lightbox2              0.5.1
  redmine_logs                   0.2.0
  redmine_questions              1.0.2
  redmine_wktime                 4.2
  redmine_xapian                 2.0.3

**Comment by CSCSxx** [comment]
After upgrading Redmine Core to 4.1.2 it works again...don't know why...but..it works ;)
